name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unshallow repo
        run: git fetch --prune --unshallow
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_API_TOKEN}}
      - name: Bump Homebrew
        uses: dawidd6/action-homebrew-bump-formula@v2
        with:
          token: ${{secrets.GITHUB_API_TOKEN}}
          formula: lazygit
